import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

import type { MetadataRoute } from 'next/server';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}

export const metadata: MetadataRoute = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
