name: AI Agent Automation
on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

jobs:
  ai-agent-handler:
    if: contains(github.event.issue.labels.*.name, 'ai-agent') || (github.event.comment && contains(github.event.comment.body, '@ai-agent'))
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Parse Issue Content
        id: parse-issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const issueBody = issue.body || '';
            
            // Extract information from issue body
            const taskType = issueBody.match(/Task Type[\s\S]*?### (.+)/)?.[1]?.trim() || 'Unknown';
            const priority = issueBody.match(/Priority[\s\S]*?### (.+)/)?.[1]?.trim() || 'Medium';
            const description = issueBody.match(/Task Description[\s\S]*?### ([\s\S]+?)###/)?.[1]?.trim() || issue.title;
            
            console.log('Parsed issue:', { taskType, priority, description });
            
            return {
              taskType,
              priority,
              description,
              issueNumber: issue.number,
              title: issue.title
            };
            
      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 **AI Agent Assigned**
              
              I've been assigned to work on this task. I'll analyze the requirements and create a pull request with the implementation.
              
              **Task Analysis:**
              - **Type:** ${{ steps.parse-issue.outputs.taskType }}
              - **Priority:** ${{ steps.parse-issue.outputs.priority }}
              - **Status:** In Progress 🔄
              
              I'll update this issue with my progress. Expected completion time: 5-10 minutes.
              `
            });
            
      - name: Add Progress Label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['in-progress', 'ai-working']
            });
            
      # This is where you would integrate with your preferred AI service
      # For now, this creates a template branch and PR
      - name: Create AI Implementation Branch
        run: |
          git config --global user.name 'AI Agent'
          git config --global user.email 'ai-agent@danielsbonnin.com'
          
          # Create a new branch for this issue
          BRANCH_NAME="ai-task-${{ github.event.issue.number }}-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          
          # Create a placeholder implementation file
          mkdir -p .ai-implementations
          cat > .ai-implementations/task-${{ github.event.issue.number }}.md << EOF
          # AI Implementation for Issue #${{ github.event.issue.number }}
          
          **Task:** ${{ github.event.issue.title }}
          
          ## Implementation Plan
          This is where the AI agent would implement the requested changes.
          
          ## Files Modified
          - List of files that would be modified
          
          ## Testing
          - Test cases that would be added
          
          ## Notes
          Implementation completed by AI Agent on $(date)
          EOF
          
          git add .
          git commit -m "AI Agent: Initial implementation for issue #${{ github.event.issue.number }}"
          git push origin "$BRANCH_NAME"
          
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🤖 AI Implementation: ${{ github.event.issue.title }}`,
              head: process.env.BRANCH_NAME,
              base: 'main',
              body: `## AI Agent Implementation
              
              This pull request was automatically created by an AI agent to address issue #${{ github.event.issue.number }}.
              
              ### Changes Made
              - Implemented requested functionality
              - Added necessary tests
              - Updated documentation if needed
              
              ### Testing
              - [ ] Manual testing completed
              - [ ] Automated tests pass
              - [ ] Code review requested
              
              **Closes #${{ github.event.issue.number }}**
              
              ---
              *Generated by AI Agent on ${new Date().toISOString()}*
              `
            });
            
            // Comment on the original issue with PR link
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Implementation Complete**
              
              I've created a pull request with the implementation: #${pr.number}
              
              Please review the changes and merge when ready!
              `
            });
            
            // Update labels
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ai-working'
            });
            
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['completed', 'ready-for-review']
            });
