name: AI Agent Automation

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  NODE_VERSION: "20"

jobs:
  validate-trigger:
    name: Validate AI Agent Trigger
    runs-on: ubuntu-latest
    permissions:
      issues: read
    outputs:
      should-process: ${{ steps.validate.outputs.should-process }}
      issue-data: ${{ steps.validate.outputs.issue-data }}
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/scripts
          
      - name: Validate Trigger Conditions
        id: validate
        uses: actions/github-script@v7
        with:
          script: |
            const { validateTrigger } = require('./.github/scripts/ai-agent/validate-trigger.js');
            return await validateTrigger({ github, context, core });